//! Build script for agent-core.
//!
//! Generates src/embedded_config.rs which declares a static ConfigSlot.
//! This symbol sits in the binary's data segment. The agent reads its own
//! executable image at runtime and scans for the config marker.
//! The C2 patches the same byte region inside any compiled agent binary.

use std::env;
use std::fs;
use std::path::PathBuf;

const MARKER_LEN: usize = 11; // b"RRA_CONFIG_V1"
const CONFIG_SIZE: usize = 512;
const PADDING: usize = CONFIG_SIZE - MARKER_LEN - 4; // 497

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let rs_path = src_dir.join("embedded_config.rs");

    let content = format!(
        "// Auto-generated by build.rs — do not edit.
// Marker occupies {total} bytes in the binary.
#[repr(C)]
pub struct ConfigSlot {{
    pub marker: [u8; {marker}],
    pub length: [u8; 4],
    pub data: [u8; {pad}],
}}

/// Placeholder — zero-filled so the symbol always lands in the binary.
pub static RRA_CONFIG_SLOT: ConfigSlot = ConfigSlot {{
    marker: [0u8; {marker}],
    length: [0u8; 4],
    data: [0u8; {pad}],
}};
",
        total = CONFIG_SIZE,
        marker = MARKER_LEN,
        pad = PADDING,
    );

    fs::write(&rs_path, &content).expect("Failed to write embedded_config.rs");
    println!("cargo::rerun-if-changed=build.rs");
}
