//! Build script for agent-core.
//!
//! Generates src/embedded_config.rs which declares a static ConfigSlot
//! with the RRA_CONFIG_V1 marker pre-populated so the C2 generator can
//! find it. The agent reads its own executable image at runtime and
//! scans for this marker.
//! The C2 patches the 512-byte config region after the marker.

use std::env;
use std::fs;
use std::path::PathBuf;

const MARKER_LEN: usize = 13; // b"RRA_CONFIG_V1"
const CONFIG_SIZE: usize = 512;
const PADDING: usize = CONFIG_SIZE - MARKER_LEN - 4; // 495

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let rs_path = src_dir.join("embedded_config.rs");

    let content = format!(
        r#"// Auto-generated by build.rs — do not edit.
// Marker occupies {} bytes in the binary.
#[repr(C)]
pub struct ConfigSlot {{
    pub marker: [u8; {}],
    pub length: [u8; 4],
    pub data: [u8; {}],
}}

/// Pre-populated marker so the C2 generator can find this slot.
#[used]
pub static RRA_CONFIG_SLOT: ConfigSlot = ConfigSlot {{
    marker: *b"RRA_CONFIG_V1",
    length: [0u8; 4],
    data: [0u8; {}],
}};
"#,
        CONFIG_SIZE, MARKER_LEN, PADDING, PADDING,
    );

    fs::write(&rs_path, &content).expect("Failed to write embedded_config.rs");
    println!("cargo::rerun-if-changed=build.rs");
}
